name: deploy

# Controls when the action will run. 
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: test github secrets
      run: |
        echo "sk_dev: ${{ secrets.SK_DEV }}"
        echo "sk_pro: ${{ secrets.SK_PRO }}" 
    
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: >
        sls config credentials 
        --provider aws 
        --key ${{ secrets.AWS_KEY }} 
        --secret ${{ secrets.AWS_SECRET }}
    - name: Deploy Lambda functions
      run: sls deploy -s dev
      working-directory: ./test

